name: Create Release
'on':
  push:
    branches:
      - main
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      
      - name: Move All Files into Code Dir
        run: mv * code | mkdir code  
        
      - name: Download encounterplus/module-packer
        run: git clone https://github.com/encounterplus/module-packer.git
        
      - name: Build Release .module File
        run: |
          cd module-packer/source/
          python3 launcher.py run --path "../../code"
          
      - name: Get Hash for Tag
        id: hash
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      
      - name: Puts the release on GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: "code/encounterspells.module"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.hash.outputs.sha_short }}
          name: ${{ steps.hash.outputs.sha_short }} - EncounterSpells
          prerelease: true
